### ISSUE TITLE
forwarding issue

### ISSUE THREAD

**Issue by matzew** [aliok/knative-backstage-demo#1]
can not open the console:

```
kubectl port-forward -n knative-backstage-demo svc/knative-backstage-demo 3000:3000
kubectl port-forward -n knative-backstage-demo svc/knative-backstage-demo 7007:7007

Forwarding from 127.0.0.1:3000 -> 3000
Forwarding from [::1]:3000 -> 3000
Handling connection for 3000
Handling connection for 3000
E0215 09:10:39.361419   11509 portforward.go:409] an error occurred forwarding 3000 -> 3000: error forwarding port 3000 to pod 60d132b6fe3628eb5c89521bea0b14cdb7c1357debffd5c525073eca071b75c5, uid : exit status 1: 2024/02/15 08:10:39 socat[23459] E connect(5, AF=2 127.0.0.1:3000, 16): Connection refused
error: lost connection to pod
Forwarding from 127.0.0.1:7007 -> 7007
Forwarding from [::1]:7007 -> 7007
```

**Comment by matzew** [comment]
The `open` util is not on linux, btw

**Comment by aliok** [comment]
Can you paste me the YAML of `knative-backstage-demo/knative-backstage-demo` Service?
Similarly, `knative-backstage-demo/knative-backstage-demo` pod YAML and logs too?

**Comment by matzew** [comment]
copy/pasta from the README

**Comment by aliok** [comment]
@matzew 

I found out why this is happening. It happens because the Backstage server is not ready yet. So, you need to wait a little...


Added the following content to the quickstart docs:

---
---

The port forwarding commands above might fail, if the Backstage server is not ready yet.

In that case, you need to wait a bit and then try again.

To make sure, you can check the logs of the `knative-backstage-demo` pod:

```
> kubectl logs -n knative-backstage-demo knative-backstage-demo
# ... wait until
# [0] <i> [webpack-dev-server] Project is running at:
# [0] <i> [webpack-dev-server] Loopback: http://localhost:3000/, http://[::1]:3000/
```
